// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $agreementsSigned_index from "./routes/agreementsSigned/index.ts";
import * as $consumer_consumer_id_layout from "./routes/consumer/[consumer_id]/_layout.tsx";
import * as $consumer_consumer_id_index from "./routes/consumer/[consumer_id]/index.ts";
import * as $consumer_consumer_id_step1 from "./routes/consumer/[consumer_id]/step1.tsx";
import * as $consumer_consumer_id_step2 from "./routes/consumer/[consumer_id]/step2.tsx";
import * as $consumer_consumer_id_step3 from "./routes/consumer/[consumer_id]/step3.tsx";
import * as $consumer_consumer_id_step4 from "./routes/consumer/[consumer_id]/step4.tsx";
import * as $consumer_consumer_id_step5 from "./routes/consumer/[consumer_id]/step5.tsx";
import * as $consumer_index from "./routes/consumer/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.ts";
import * as $oidc from "./routes/oidc.ts";
import * as $profile from "./routes/profile.tsx";
import * as $prosumer_prosumer_id_layout from "./routes/prosumer/[prosumer_id]/_layout.tsx";
import * as $prosumer_prosumer_id_step1 from "./routes/prosumer/[prosumer_id]/step1.tsx";
import * as $prosumer_prosumer_id_step2 from "./routes/prosumer/[prosumer_id]/step2.tsx";
import * as $prosumer_prosumer_id_step3 from "./routes/prosumer/[prosumer_id]/step3.tsx";
import * as $prosumer_index from "./routes/prosumer/index.tsx";
import * as $provider_provider_id_step1 from "./routes/provider/[provider_id]/step1.tsx";
import * as $provider_index from "./routes/provider/index.tsx";
import * as $test from "./routes/test.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $consumer_ConsumerStep1 from "./islands/consumer/ConsumerStep1.tsx";
import * as $prosumer_ProsumerStep1 from "./islands/prosumer/ProsumerStep1.tsx";
import * as $prosumer_ProsumerStep2 from "./islands/prosumer/ProsumerStep2.tsx";
import * as $prosumer_ProsumerStep3 from "./islands/prosumer/ProsumerStep3.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
    routes: {
        "./routes/_404.tsx": $_404,
        "./routes/_app.tsx": $_app,
        "./routes/_layout.tsx": $_layout,
        "./routes/_middleware.tsx": $_middleware,
        "./routes/agreementsSigned/index.ts": $agreementsSigned_index,
        "./routes/consumer/[consumer_id]/_layout.tsx": $consumer_consumer_id_layout,
        "./routes/consumer/[consumer_id]/index.ts": $consumer_consumer_id_index,
        "./routes/consumer/[consumer_id]/step1.tsx": $consumer_consumer_id_step1,
        "./routes/consumer/[consumer_id]/step2.tsx": $consumer_consumer_id_step2,
        "./routes/consumer/[consumer_id]/step3.tsx": $consumer_consumer_id_step3,
        "./routes/consumer/[consumer_id]/step4.tsx": $consumer_consumer_id_step4,
        "./routes/consumer/[consumer_id]/step5.tsx": $consumer_consumer_id_step5,
        "./routes/consumer/index.tsx": $consumer_index,
        "./routes/index.tsx": $index,
        "./routes/login.ts": $login,
        "./routes/oidc.ts": $oidc,
        "./routes/profile.tsx": $profile,
        "./routes/prosumer/[prosumer_id]/_layout.tsx": $prosumer_prosumer_id_layout,
        "./routes/prosumer/[prosumer_id]/step1.tsx": $prosumer_prosumer_id_step1,
        "./routes/prosumer/[prosumer_id]/step2.tsx": $prosumer_prosumer_id_step2,
        "./routes/prosumer/[prosumer_id]/step3.tsx": $prosumer_prosumer_id_step3,
        "./routes/prosumer/index.tsx": $prosumer_index,
        "./routes/provider/[provider_id]/step1.tsx": $provider_provider_id_step1,
        "./routes/provider/index.tsx": $provider_index,
        "./routes/test.tsx": $test,
    },
    islands: {
        "./islands/Sidebar.tsx": $Sidebar,
        "./islands/consumer/ConsumerStep1.tsx": $consumer_ConsumerStep1,
        "./islands/prosumer/ProsumerStep1.tsx": $prosumer_ProsumerStep1,
        "./islands/prosumer/ProsumerStep2.tsx": $prosumer_ProsumerStep2,
        "./islands/prosumer/ProsumerStep3.tsx": $prosumer_ProsumerStep3,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
