version: "3"

dotenv: [".env"]

tasks:
  default:
    cmd:
      deno task start
  compile:
    cmd:
      deno compile --include static --include fresh.config.ts --include fresh.gen.ts --include deno.json -A --unstable-kv main.ts
  docker:
    cmd:
      docker build --build-arg GIT_REVISION=$(git rev-parse HEAD) -t fresh-aimaas-ui .
