export interface ConsumerState {
    currentStepIndex: number;
    maxStepProgress: number;
}

export interface DomainAttr {
    id: number;
    domain_id: number;
    name: string;
}
export interface Domain {
    id: number;
    name: string;
    description: string;
    attributes: DomainAttr[];
}

export interface User {
    id: string;
    name: string;
    email: string;
    tokens: { id_token: string; access_token: string; expires_in?: number; expires_at?: number };
    session_id: string;
}

export interface ModelSearchAttributeCriterion {
    attribute: DomainAttr;
    value: string;
}
export interface ModelSearchCriterion {
    domain: Domain;
    attributes: ModelSearchAttributeCriterion[];
}

export interface ModelSearchResponseItem extends Record<string, unknown> {
    id: number;
}

export interface SSISearchCriterion {
    domain: Domain;
    attribute: DomainAttr;
    operator: "equal";
    value: string;
}
export type SSISearchStatus = "NOT STARTED" | "ACCEPTED" | "FINISHED" | "ERROR";
export interface SSISearchResponse {
    status: SSISearchStatus;
    process_id?: string;
}
export interface SSISearchPollResponse {
    status: SSISearchStatus;
    datasets_ids?: string[];
}

export type ProcessStatus = "NOT STARTED" | "IN PROGRESS" | "FINISHED" | "BLOCKED" | "FAILED";

export interface ProsumerWorkflowSSIData {
    process_id: string;
    status: SSISearchStatus;
    criteria: SSISearchCriterion[];
    results?: string[]; // Results, "datasets ids"
}

export interface ProsumerWorkflowData {
    readonly id: string; // "prosumer id"
    name: string;
    ssi: ProsumerWorkflowSSIData; // this is for "step 1"
}

export interface ConsumerWorkflowData {
    readonly id: string; // "consumer id"
    step1_search: ModelSearchCriterion; // this is for "step 1"
    step1_results?: ModelSearchResponseItem[];
    selected_model_id?: number; // if it was selected then we have redirected to STM
    agreements_signed?: boolean; // if this is not undefined then we have get the response from the STM
    model_downloaded?: boolean;
}

/*

Example:
{
  "data-provider-IDs": ["8", "9"],
  "model-consumer-endpoint": "https://trustee-test-hedf-mc.cybersec.digital.tecnalia.dev",
  "computation": "Simple Averaging",
  "process-ID": "test-MultiFL-018",
  "number-of-rounds": 2
}

Field Descriptions:

| Field                     | Type   | Description                                           |
| --- ----------------------| ------ | -------------------------                             |
| data-provider-IDs         | array  | List of data provider IDs, retrieved from DL (exists) |
| model-consumer-endpoint   | string | Provided by the user (exists) |
| computation               | string | Computation type (e.g., "Simple Averaging") (exists) |
| process-ID                | string | Unique process identifier, generated by the UI (exists) |
| number-of-rounds          | int    | Number of FL rounds, must be > 0 (tbd) |

*/

export interface FLStartAggregationRequest {
    dataProviderIDs: string[]; // json: "data-provider-IDs"
    modelConsumerEndpoint: string; // json: "model-consumer-endpoint"
    computation: string; // json: "computation"
    processID: string; // json: "process-ID"
    numberOfRounds: number; // json: "number-of-rounds"
}
