export interface ConsumerState {
    currentStepIndex: number;
    maxStepProgress: number;
}

export interface DomainAttr {
    id: number;
    domain_id: number;
    name: string;
}
export interface Domain {
    id: number;
    name: string;
    description: string;
    attributes: DomainAttr[];
}

export interface User {
    id: string;
    name: string;
    email: string;
    tokens: {
        id_token: string;
        access_token: string;
        expires_in?: number;
        expires_at?: number;
    };
    session_id: string;
}

export interface ModelSearchAttributeCriterion {
    attribute: DomainAttr;
    value: string;
}
export interface ModelSearchCriterion {
    domain: Domain;
    attributes: ModelSearchAttributeCriterion[];
}

export interface ModelSearchResponseItem extends Record<string, unknown> {
    id: number;
}

export interface SSISearchCriterion {
    domain: Domain;
    attribute: DomainAttr;
    operator: "equal";
    value: string;
}
export type SSISearchStatus = "NOT STARTED" | "ACCEPTED" | "FINISHED" | "ERROR";
export interface SSISearchResponse {
    status: SSISearchStatus;
    process_id?: string;
}
export interface SSISearchPollResponse {
    status: SSISearchStatus;
    datasets_id?: string[];
}

export type ProcessStatus =
    | "NOT STARTED"
    | "IN PROGRESS"
    | "FINISHED"
    | "BLOCKED"
    | "FAILED";

export interface ProsumerWorkflowSSIData {
    process_id: string;
    status: SSISearchStatus;
    criteria: SSISearchCriterion[];
    results?: string[]; // Results, "datasets ids"
}

export interface ProsumerWorkflowFLData {
    process_id: string;
    status: string;
    current_round: number;
    number_of_rounds: number;
    models: string[];
    computation: string;
    solver: string;
    denoiser: string;
    num_of_iterations: number;
}

export interface ProsumerWorkflowData {
    readonly id: string; // "prosumer id"
    name: string;
    ssi: ProsumerWorkflowSSIData; // this is for "step 1"
    models_selected: string[]; // step2 when completed fills this
    fl_process?: ProsumerWorkflowFLData; // step3 fills the fl parameters and starts FL process
}

export interface ConsumerWorkflowData {
    readonly id: string; // "consumer id"
    step1_search: ModelSearchCriterion; // this is for "step 1"
    step1_results?: ModelSearchResponseItem[];
    selected_model_id?: number; // if it was selected then we have redirected to STM
    agreements_signed?: boolean; // if this is not undefined then we have get the response from the STM
    model_downloaded?: boolean;
}

/*

Example:
{
  "data-provider-IDs": ["8", "9"],
  "model-consumer-endpoint": "https://trustee-test-hedf-mc.cybersec.digital.tecnalia.dev",
  "computation": "Simple Averaging",
  "process-ID": "test-MultiFL-018",
  "number-of-rounds": 2
}

Field Descriptions:

| Field                     | Type   | Description                                           |
| --- ----------------------| ------ | -------------------------                             |
| data-provider-IDs         | array  | List of data provider IDs, retrieved from DL (exists) |
| model-consumer-endpoint   | string | Provided by the user (exists) |
| computation               | string | Computation type (e.g., "Simple Averaging") (exists) |
| process-ID                | string | Unique process identifier, generated by the UI (exists) |
| number-of-rounds          | int    | Number of FL rounds, must be > 0 (tbd) |

*/

export interface FLStartAggregationRequest {
    dataProviderIDs: string[]; // json: "data-provider-IDs"
    modelConsumerEndpoint: string; // json: "model-consumer-endpoint"
    computation: string; // json: "computation"
    processID: string; // json: "process-ID"
    numberOfRounds: number; // json: "number-of-rounds"
}

export interface ProviderWorkflowData {
    readonly id: string; // "provider id"
    name?: string;
    model_description?: string; // step1: model description
    domain_id?: number; // step1: domain id
    credential_id?: string; // step1: credential id
    model_provider_id?: string; // step1: model provider id (user's sub)
    source_url?: string; // step1: source url
    ecosystem?: string; // step1: ecosystem (Trustee, Gaiax, Copernicus, IDS)
    trustworthiness_assessment?: string; // step2: trustworthiness assessment status
    privacy_impact_assessment?: string; // step3: privacy impact assessment status
    gdpr_compliance_check?: string; // step4: gdpr compliance status
    agreements_signed?: boolean; // step5: agreements signed status
    model_uploaded?: boolean; // step6: model and files uploaded
}
